arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base
    - epaule
    - coude
    - poignet_incl
    - poignet_rot
  gains:
    base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    epaule:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    coude:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    poignet_incl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    poignet_rot:
      p: 100
      d: 1
      i: 1
      i_clamp: 1