controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base
      - epaule
      - coude
      - poignet_incl
      - poignet_rot
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - pince_mot
      - pince_lib